### ISSUE TITLE
Behavior when specifying directory

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#139]
Open question: what should be the default behavior if a directory is given?
At the moment we throw and error and stop. Instead, the user has to use a `glob` pattern for recursion, e.g. `**/*.md`.
That doesn't seem to be very intuitive right now. See https://github.com/lycheeverse/lychee-action/issues/3.

Here's my proposal:
If the user specifies a single directory, analyze all supported files (currently html/md/txt) within that directory.
This also holds if the user specifies a glob that implies a directory. 

Any objections or concerns?

**Comment by joesan** [comment]
Could we just show the usage and quit? I mean error out but hinting the user with a proper message on how to specify the glob pattern for the directory.

**Comment by mre** [comment]
That would work. My main question is what a user expects when specifying a directory.
E.g. when they run `lychee docs/`, they probably have some standard behavior in mind. At least I would think that this is checking all known files within the `docs` folder, but I want to hear other people's opinion on that before making a call.

**Comment by polarathene** [comment]
Probably makes sense for just checking files within that directory level, but not nested directories that would require a glob pattern. At least, users may be familiar with that with something like `ls` or `.gitignore`(kinda different since it'd ignore the full subtree in this case) when passing a directory?

Otherwise bailing to inform the user that they probably meant `directory/*` (all files in directory) or `directory/**` (all files in subtree) seems fine.

The fact that a user may be unsure which of those two globbing outcomes would occur may make it better to throw the error and ask the user to be a bit more specific with what they'd like.

**Comment by mre** [comment]
You are right. Bailing makes sense as the behavior is ambiguous. Even worse, the link check could skip over files that the user thinks were included. Happy to accept a PR here.

**Comment by mre** [comment]
(Just also want to point out that @joesan had the same idea and that I like the teamwork on this one. 😆)

**Comment by mre** [comment]
>  If the user specifies a single directory, analyze all supported files (currently html/md/txt) within that directory.

This is supported in `master` now after #330 got merged. 🎉 

If multiple directories are given as arguments and one cannot be read it will exit with an error message as well.
