### ISSUE TITLE
Missing 0.15.x releases on docker hub

### ISSUE THREAD

**Issue by FlorianLudwig** [lycheeverse/lychee#1432]
On docker hub no tags for 0.15 releases can be found:

https://hub.docker.com/r/lycheeverse/lychee/tags?page=&page_size=&ordering=&name=0.15

**Comment by thomas-zahner** [comment]
Thanks for reporting. Hmm, for some reason the release pipeline did not publish them..
We re-ran them manually so `0.15.0` and `0.15.1` [are now available](https://hub.docker.com/r/lycheeverse/lychee/tags?page=&page_size=&ordering=&name=0.15)

**Comment by eread** [comment]
@thomas-zahner @mre It looks like this persists with the last couple of versions also. Only SHA tags, no version tags.

**Comment by mre** [comment]
It feels like we broke it when switching to release-plz. [I tried to re-run the pipeline](https://github.com/lycheeverse/lychee/actions/runs/11799525793/job/32868236741), but it didn't create a new version tag. Not entirely sure how to fix it. Maybe someone has an idea.

**Comment by eread** [comment]
> It feels like we broke it when switching to release-plz. [I tried to re-run the pipeline](https://github.com/lycheeverse/lychee/actions/runs/11799525793/job/32868236741), but it didn't create a new version tag. Not entirely sure how to fix it. Maybe someone has an idea.

@mre I noticed at the bottom of _Push Image (debian)_ https://github.com/lycheeverse/lychee/actions/runs/11708052907/job/32608866699 this warning:

> WARNING: No output specified with docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load

Looking at the project docs at: https://github.com/docker/build-push-action, it looks like you might need to set `with.push = true` to have the push actually happen.

Because that isn't set anywhere in this project, I don't understand how any pushes are happening.

I wonder if anything has changed at: https://github.com/docker/build-push-action/releases? 🤔

**Comment by mre** [comment]
Very interesting. I think it pushed in the past at least -- otherwise there would be no images. But yeah, we should set that. If you like, you could add it and we'll give it a shot?

**Comment by eread** [comment]
> Very interesting. I think it pushed in the past at least -- otherwise there would be no images. But yeah, we should set that. If you like, you could add it and we'll give it a shot?

@mre I think I figured it out!

Looking more closely (not sure why I missed this before): https://github.com/lycheeverse/lychee/blame/master/.github/workflows/docker.yml, there's:

```yaml
push: ${{ github.event_name != 'pull_request' && github.actor != 'dependabot[bot]' }}
```

That's been in place for a while: https://github.com/lycheeverse/lychee/commit/6887543105370d73c5559c0a5f4eb924a86fe070, so at some point that's stopped evaluating to `true` when releases are cut.

I think that's happened because you've started raising pull requests for releases, like: https://github.com/lycheeverse/lychee/pull/1549. I think all the "missing" releases are ones released using pull requests.

So it seems we need to figure out how have that evaluate on some pull requests (release PRs), but not all.

**Comment by eread** [comment]
@mre I've raised: https://github.com/lycheeverse/lychee/pull/1568 to try and figure this out.
