### ISSUE TITLE
Analysis gets stuck with --github-token flag

### ISSUE THREAD

**Issue by Ludsrill** [lycheeverse/lychee#209]
I am trying to analyze around 7000 links of all kinds, but when I use the --github-token flag this gets slower and slower until it definitely gets stuck ending the analysis for no apparent reason.

This problem is happening to me on Windows and a virtual machine running ubuntu 18.04

**Comment by mre** [comment]
That's not good. 
Usually you should get a 429 (Too Many Requests) in that case, but it should fail immediately.
Is the list of links public somewhere, so we can I can try it on my side?
Does it finish if you don't set a GitHub token? 

Long-term, we should move to website-based rate-limiting (#36).

**Comment by Ludsrill** [comment]
I'm going to try to extract the list of links so you can try to reproduce the problem.

This problem doesn't exist if I remove the flag, but obviously, all GitHub links gonna fail, which is a problem for me, so I decided  to use the --exclude flag to avoid GitHub links, for now, in that way it worked without problems

**Comment by Ludsrill** [comment]
Here, there are 5889 links, the problem starts when lychee has analyzed about 5860 links 

[LINKS.txt](https://github.com/lycheeverse/lychee/files/6259497/LINKS.txt)

**Comment by mre** [comment]
Thanks for compiling the list. Just tested on my computer and it works.
Without setting the Github token, the process takes about 1 minute.
With the Github token, it takes 2:30min. 
The reason is, that without the Github token I get a 429 immediately, while setting it results in a 200, but it takes very long to process all items in the queue. It doesn't get stuck, though.

To avoid overloading the system, you could play around with some more conservative settings: 
```
lychee --verbose --timeout 5 --max-redirects 0 --max-concurrency 5 --include github.com -- LINKS.txt
```

Apart from that, the better solution would be to add a domain-based rate-limiter (#36) in the future.

**Comment by Ludsrill** [comment]
That completely solves the problem

thanks for your help!!
