### ISSUE TITLE
Falied to read local file due to `stream did not contain valid UTF-8` but its remote version it is successfully read

### ISSUE THREAD

**Issue by micalevisk** [lycheeverse/lychee#215]
Hey! basically what the title says. I've test it on GitHub's Ubuntu. 

https://github.com/lycheeverse/lychee/blob/33e952b428c165aa55f3eee133555c9d53b469aa/src/collector.rs#L119-L121

## steps to reproduce

```bash
$ lychee https://raw.githubusercontent.com/jwasham/coding-interview-university/main/translations/README-bn.md

📝 Summary
---------------------
🔍 Total..........732
✅ Successful.....581
⏳ Timeouts........20
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors.........131

# ...
```
 
```
$ wget https://raw.githubusercontent.com/jwasham/coding-interview-university/main/translations/README-bn.md
$ lychee README-bn.md
Error: Failed to read file: `README-bn.md`

Caused by:
    stream did not contain valid UTF-8
```

I think this a bug.

**Comment by mre** [comment]
We read the input into a String and expect UTF-8.
So this also fails:

```rust
use std::fs;

fn main() -> Result<(), Box<dyn std::error::Error + 'static>> {
    fs::read_to_string("README-bn.md")?;
    Ok(())
}
```

With the same error:

```
Error: Custom { kind: InvalidData, error: "stream did not contain valid UTF-8" }
```

That means, the document doesn't contain UTF-8.
More specifically, the input file is UTF-16:

```
file README-bn.md
README-bn.md: Little-endian UTF-16 Unicode text, with CRLF line terminators
```

It was most likely created on Windows.

Now the question is if we should _expect_ valid UTF-8 at all. I don't think so, because there are other file formats, which should be completely fine. However, pulldown-cmark (our Markdown parser) seems to only accept `&str` &mdash; string slices, which are are [always valid UTF-8](https://doc.rust-lang.org/std/primitive.str.html) in Rust.

Here's the parser struct we use: https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/struct.Parser.html#method.new
Since pulldown-cmark is hard to beat in functionality and robustness, I'd say that's a bit of a blocker.
One could convert the UTF-16 document to UTF-8 or work on `OsString` or bytes, but then Markdown parsing will take us for a ride. 😆 
That's probably also why pulldown-cmark doesn't support other formats: it's hard.

I'm not aware of a good alternative. 😕

**Comment by micalevisk** [comment]
Got it! thanks. Now, to me, this behavior is desired, isn't bug :P

I'm trying to use the GitHub Action to check the links in that repo (which I don't have any control). I'll filter the file's encoding to use lychee using the remote link instead of the local file. Or maybe I'll just convert files to UTF-8 before.

**Comment by sschuberth** [comment]
BTW, the same happens when checking https://github.com/hapijs/address/blob/v2.1.4/README.md locally. But in any case, IMO a "stream did not contain valid UTF-8" error should not stop checking any remaining files like it doe snot, but simply skip the offending file.

**Comment by mre** [comment]
The risk is that when used in CI, the user might not see the issue if it doesn't lead to an error, which could cause the pipeline to run, but skip some or all files. The result would be a successful job, but it would hide errors.

**Comment by mre** [comment]
We have `ignore-missing-inputs`, which could be used to continue with the other inputs in that case. However it serves a slightly different purpose, so `--ignore-input-errors` could be introduced. Before we do that, I'd like to learn if more people face this issue, as I want to avoid having too many flags (which won't get used 99% of the time).

**Comment by sschuberth** [comment]
I'm not necessarily saying it should not lead to an error in the end, but remaining files should be scanned, and if any of the files had errors, report that.

**Comment by mre** [comment]
Interesting idea. Not 100% sure at the moment, but we should move that discussion elsewhere. As it's not an issue with lychee per se, would you mind to start an actual discussion for it? I want others to chime in and collect feedback on the proposal.

**Comment by sschuberth** [comment]
> As it's not an issue with lychee per se, would you mind to start an actual discussion for it?

Done: https://github.com/lycheeverse/lychee/discussions/1048 (though I don't agree it's not an issue with lychee per se; other tools collect errors by default and have something like `--fail-fast` to change that behavior).
