### ISSUE TITLE
Status of unused dependencies

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#223]
There are a few unused dependencies
- `openssl_sys`
- `ring`

`ring` is supposed to solve build issue on Apple M1 architecture. But is it still needed?
Someone mentioned that `exa` had the issue and `ring` can solve it. But how? There's no
`use ring` in the entire crate. Also, I don't see anything mentioned about `ring`, either
in its manifest, or in the homebrew recipe: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/exa.rb

Also, `ring` at least should be gated behind a `cfg` attribute for darwin only.

Similarly, `openssl_sys` is never used. Could that be safely removed?

**Comment by mre** [comment]
hubcaps [depends on jsonwebtoken 7](https://github.com/softprops/hubcaps/blob/a9e6616ecc7b8eef0ea0eaf6055d9610c8961500/Cargo.toml#L29), which [depends on ring](https://github.com/Keats/jsonwebtoken/blob/2f25cbed0a906e091a278c10eeb6cc1cf30dc24a/Cargo.toml#L17), which is [not ready for Apple Silicon](https://github.com/briansmith/ring/issues/1163). The advice is to explicitly depend on a newer version which does. (See `cargo tree --invert ring` in lychee.)

`openssl_sys` can't build on macOS with the openssl bindings ([issue](https://github.com/sfackler/rust-openssl/issues/1409)), which is why we use ring to statically link SSL support.

At least that's what I think is going on. It's all a bit of a mess. 🤷‍♀️

**Comment by mre** [comment]
But I'd be more than happy to remove that or at least put it behind a gate.
Also, maybe we should be good OSS citizens and get send PRs to the deps in question.

**Comment by lebensterben** [comment]
Also I think we should have a new feature flag `serde` that controls whether `serde` is enabled for dependencies.

**Comment by mre** [comment]
Good idea. 👍

**Comment by lebensterben** [comment]
As for `ring` and `openssl_sys`, I confirm that they cannot be built for `aarch-apple-darwin` target.
`hubcaps` requires `ring`. So one simple solution is to replace it with `github_rs`.

**Comment by mre** [comment]
Can we close this?

**Comment by lebensterben** [comment]
not really..
They're not added to optional dependencies yet.

**Comment by mre** [comment]
This has been in the queue for a while. @lebensterben do you want to tackle this? I personally don't have the resources right now. 😕

**Comment by mre** [comment]
Closing this to keep the issue tracker clean. @lebensterben, feel free to reopen if you're planning to work on this. 😉
