### ISSUE TITLE
Handle unknown status codes

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#234]
A Lychee worker panics when encountering a website with an invalid and unaccepted status code.
For example, LinkedIn returns the status code 999 by default.

```
echo https://www.linkedin.com/in/endlermatthias | lychee -
```

This results in the following output:

```
thread 'tokio-runtime-worker' panicked at 'internal error: entered unreachable code', lychee-lib/src/types/status.rs:67:21
```

A workaround is to accept the status code like so:

```
echo https://www.linkedin.com/in/endlermatthias | lychee - --accept 999
```

Also we can handle LinkedIn with a quirk by using a different user agent.

But in general we are missing a case where a request returns an unexpected status code here:

https://github.com/lycheeverse/lychee/blob/d651b1ef7bb6e42cf96c334be3556c71a5574293/lychee-lib/src/types/status.rs#L60-L68

@lebensterben is that something you could tackle?

**Comment by lebensterben** [comment]
M$ is evil.😡

See this https://stackoverflow.com/questions/27231113/999-error-code-on-head-request-to-linkedin


It's reported that:
- Its server filters both UA and IP
- There's a rate limit of several dozens request per day

Changing UA is probably best thing we can do.
Accepting a different status code is weird. Because 999 is a legitimate error. If we accept it we don't have a way to identify a real 999 error.

**Comment by lebensterben** [comment]
BTW.
I'm currently working on some other stuff now. I'm likely to be occupied by them this month.

**Comment by mre** [comment]
> Changing UA is probably best thing we can do.

👍 

>  Accepting a different status code is weird. Because 999 is a legitimate error. If we accept it we don't have a way to identify a real 999 error.

True. Let's just make sure we don't panic when we encounter that case, but handle it gracefully instead. 😆 

>  I'm currently working on some other stuff now. I'm likely to be occupied by them this month.

No worries. If anyone else has to the time to look into it before, feel free to add a comment here.

**Comment by mre** [comment]
Question: from an API perspective, would you rather expect to get a valid status like `Status::Other(999)` in that case or an error like `ErrorKind::StatusCodeError(code)`?
I'd say it's not really an error, because we can always hit an unexpected status code like 123456. But it also feels weird to have an "Other" type for any status we don't understand. 🤔

**Comment by lebensterben** [comment]
Is it possible to have non standard status code? Is it supported by reqwest client?

**Comment by mre** [comment]
Yeah, `reqwest` supports status codes up to 999:
https://docs.rs/reqwest/0.11.3/reqwest/struct.StatusCode.html

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=024b928f430609198616e59c8ea95eb5

**Comment by mre** [comment]
My idea is to accept everything that reqwest accepts and return an error for invalid status codes.

**Comment by lebensterben** [comment]
What I was asking is, is it possible to have status code > 999...

**Comment by lebensterben** [comment]
Probably it's possible to have any status code.
But if the server side is correctly implemented, it should never ever return non standard status code...

**Comment by mre** [comment]
The web is a weird place. I'm pretty sure we'd be able to find any status code we'd like out there. 😉 lychee shouldn't panic in any case.

**Comment by lebensterben** [comment]
that's right.

Something like `ErrorKind::StatusCodeError(code)` should be the way to handle this.

But the name can be more informative, like "UnknownStatusCode". Basically it catches any code > 999. But it cannot catch the case when the server attach non-standard meanings to status code. That's something we cannot cover.

**Comment by lebensterben** [comment]
Also, if we found some website returning non standard status code, we may emit a special warning (in addition to the error message it self) in the output.

This is because, should a server going rogue, i.e. sending non standard status code, we would not be sure the 200 status code means it's OK.

There are different strategies when such case occured:
- Halt all threads and add the domain/host to exclude list, then continue.
- Don't change anything, but in the end don't classify the links from questionable domain as success/timeout/etc. They's be classified as Unknown.
