### ISSUE TITLE
Support deny list

### ISSUE THREAD

**Issue by ylwu-amzn** [lycheeverse/lychee#267]
## Problem
We migrate our public documents to a new URL and we need to check if there are old links. But seems `lychee` doesn't support deny list currently.

## How to solve
Can you support new option like `--deny *abc.com/*`, so we can check if there is old links and can fail quickly.

**Comment by lebensterben** [comment]
Just use `--exclude`

**Comment by ylwu-amzn** [comment]
Thanks @lebensterben. I think `--exclude ` means we will exclude these links and just skip checking them, right?

**Comment by lebensterben** [comment]
okay I misunderstood you question.

**Comment by lebensterben** [comment]
lychee is a link checker, which mainly verify whether a given link is valid, by testing whether it's accessible.

If you want to make certain URL patterns fail regardless of whether it's actually accessible, I don't think it's really what a link checker should do.

If, for example, you want to blacklist a whole IP or domain, you can add it to /etc/hosts with a `localhost`, `loopback`, etc.

**Comment by MichaIng** [comment]
To find specific URLs in your website repository, `grep` should work fine:
```sh
grep -r 'abc.com' .
```
This  searches recursively through all plain text files (including HTML) from the current working directory and prints all matches, including the file name. Since this is something that needs to be done once only, it does not require to do any HTTP connection check and there are native system tools to check for patterns, I agree that it is not a feature that makes sense in a link checker.

**Comment by ylwu-amzn** [comment]
> To find specific URLs in your website repository, `grep` should work fine:
> 
> ```shell
> grep -r 'abc\.com' .
> ```
> 
> This searches recursively through all plain text files (including HTML) from the current working directory and prints all matches, including the file name. Since this is something that needs to be done once only, it does not require to do any HTTP connection check and there are native system tools to check for patterns, I agree that it is not a feature that makes sense in a link checker.

Thanks. That's what we are doing now to use grep.
One concern is that some developer may put old website links in code and they are not aware of that. If `lychee` can support this, we can automatically check this with Github action. That can avoid manual effort.

**Comment by mre** [comment]
Would https://github.com/lycheeverse/lychee/pull/99 work for you?
It wouldn't perform any link checking. Instead, it dumps all the links extracted from inputs that would be checked.

**Comment by MichaIng** [comment]
Is it really that much effort to add a dedicated `grep` job to a workflow compared to an additional argument for the existing `lychee` workflow?

I'm currently not sure which user agent `lychee` has, but another approach would be to block the request based on it webserver-side. Or add a hosts entry on the GitHub actions VM so that `lychee` fails to resolve that domain (**EDIT: Ah, already mentioned by `@lebensterben` above**).

But I get the idea. Not sure how much effort such an "always fail on pattern" option is and whether too many options is seen negative as well.
__________
@mre 
I think the idea is to combine it with a regular check, but explicitly fail on certain URL pattern. The dry run would dump and skip all URLs. Ah but at least it can be used in combination with grep more effectively:
```sh
! ./lychee ... | grep -q 'abc\.com'
```

**Comment by ylwu-amzn** [comment]
Thanks @MichaIng , this looks good `! ./lychee --no-check [...] | grep -q 'abc\.com'`

**Comment by lebensterben** [comment]
Well, if we redefine `lychee` as both a link ___checker___ and a link ___linter___, then this feature request is for the linter capability.

**Comment by mre** [comment]
@ylwu-amzn, this should now be possible in `master`:

```
! ./lychee --dump [...] | grep -q 'abc\.com'
```

Note that the flag is called `--dump` and not `--no-check` as initially proposed. Discussion and PR here: #99. 
There was a small issue related to pipes that was fixed in https://github.com/lycheeverse/lychee/pull/340.

**Comment by mre** [comment]
Closing this as there is a solution now using `--dump` (see above).
