### ISSUE TITLE
feature request : blacklist schemes

### ISSUE THREAD

**Issue by ajoga** [lycheeverse/lychee#297]
It would be nice to be able to blacklist some schemes like `unix://` on top of the actual possibility of whitelisting them. That way I could catch typos like `hhtp://`

**Comment by MichaIng** [comment]
Unsupported schemes are silently skipped since #236 (not yet part of the latest release), which makes sense to not fail on every `ftp://`, `sftp://`, `data://`, `chrome://` etc, including your `unix://` example.

This means that typos in the scheme are silently ignored as well. But when there is a typo in such an essential part of the URL, then there is no guarantee anyway that any link checker will detect it as URL, so we should not start to try this. E.g. `http:/example.org` is a similar typo, but the first part is not even detectable as URL scheme at all. Skipping it silently but failing on `hhtp://` IMHO is not a consistent or desired behaviour.

**Comment by ajoga** [comment]
Understandable, thank you!
