### ISSUE TITLE
Error with base dir `<empty>` 

### ISSUE THREAD

**Issue by ran-huang** [lycheeverse/lychee#320]
Hi, I use Lychee in GitHub Actions, which worked perfectly until this week. I got this error today:

```
Error: Error with base dir `<empty>` : Found absolute local link "/download" but no base directory was set. Set with `--base`.
+ exit_code=1
```

I tried to add `--exclude /download` in args, but the error persists. It still checks `/download`. 

I can't set `--base` because it will affect other relative links with different base URL. Is there a way to fix the error? Thank you!

**Comment by MichaIng** [comment]
Do you use the latest stable release v0.7.1 or build it from master? Dump question, as it says `--base` instead of `--base-url` so it must be the master branch 😄.

Local file check support has been added: #262
This means you can use a base path now instead of a base URL and lychee will then not do a network request for internal links but instead check if the file/dir exists locally. Probably this solves your issue with the different base URLs? Else it may make sense to check the websites for different domains/hosts with dedicated lychee calls so that you can define the correct base path (or URL) separately, to have internal links with absolute paths checked as well. For those with relative paths, local file/dir checking is done automatically resolving the relative path in the directory tree.

But before this feature was added, internal links with absolute paths were silently ignored if no `--base-url` was given, if I'm not mistaken. And I think this should be kept instead of throwing an error. Probably a warning like [here](https://github.com/lycheeverse/lychee/commit/e188e72fc0cecffbaf07f3428550886c3f0003a0) or a silent exclusion like for [unsupported schemes](https://github.com/lycheeverse/lychee/pull/236) makes sense @mre?

Another thing is that `--exclude`s should probably be skipped before any further check on the URL is done.

**Comment by mre** [comment]
I see three options moving forward:
1. We silently ignore internal links with absolute paths.
2. We print a warning but check the rest
3. We assume the input directory as the base for absolute links if no base is set.

In the long run I lean towards option 3. It would be what I expect if I run `lychee public/` for example where `public` is the build directory of a static site generator. 
It gets tricky when we look at multiple inputs. Then we'd have to track the input source for each link to determine the base. We could add a `source` field to the `Input`, which would allow us to backtrack the source of each link for that use-case.

This requires quite some refactoring, so in the meantime we could go with option 1 to not break any existing user workflows.

**Comment by MichaIng** [comment]
I vote for option 1 + adding a note to the usage that `--base` is required to check relative URLs with absolute path (or "internal links with absolute path", not sure how to name precisely + understandable). If option 2, then I fear we'd need another CLI option to allow muting it. There may be cases where files with different base paths/URLs are aimed to be checked in a single run, so that setting a base would be right for some but wrong for others.

Option 3 would imply too many assumptions and/or complicated checks and steps to do it mostly right, IMHO. Better to force users being explicit about what they want than being too implicit with much effort and always the chance to still assume wrong.

**Comment by mre** [comment]
You have a good point there. I changed my mind. Unless anyone else brings up a good argument against it, let's go with option 1.

**Comment by ran-huang** [comment]
Thank you! This issue is fixed. ❤️
