### ISSUE TITLE
Improve docker container publishing

### ISSUE THREAD

**Issue by fauust** [lycheeverse/lychee#321]
Hi!
Based on what was done in #40, I see some stuff that could be improved.
- **multi-arch**: publish other architectures (see https://hub.docker.com/_/debian?tab=tags&page=1&ordering=last_updated&name=buster-slim):
  Would complexify a bit the CI, so this could increase maintenance burden, see https://github.com/fauust/docker-systemd/blob/master/.github/workflows/build.yml or https://github.com/mvdan/sh/blob/master/.github/workflows/test.yml. But providing other arch is good for adoption IMO and you already provide multi-arch binaries.
- **description**: update the README.md on https://hub.docker.com/r/lycheeverse/lychee/, this would permit to have an overview directly on dockerhub:
   Quite easy to implement, see https://github.com/fauust/docker-systemd/blob/master/.github/workflows/build.yml#L131-L138

If you feel this is good to have, let me know and I will prepare it.

**Comment by lebensterben** [comment]
Is multi arch really needed?
Is anyone seriously running lychee with it?

**Comment by fauust** [comment]
> Is multi arch really needed?

good, Q. Why providing lychee binaries for aarch64 and arm then?

> Is anyone seriously running lychee with it?

What do you mean with seriously?

**Comment by MichaIng** [comment]
Running a static binary on an ARM system is quite some difference from running a whole Docker container on an ARM system for having a single tool available. I personally use lychee by times on ARM SBCs, but the static binaries, while it would never cross my mind to spin up a Docker container for it.

On an ARM M1 with macOS there are no static binaries available, but those ARMs are capable to think about running such tools in a container, so there may be some use case. Not sure about Windows 11 with some rumours that it will run on a Raspberry Pi, but on such a little ARM spinning up a container for such tool is quite nonsense, at least when doing link checks is not the only task it does 😄.

OOT: When talking about M1 with macOS, this may be a reason to provide static ARM binaries for macOS?

**Comment by fauust** [comment]
> Running a static binary on an ARM system is quite some difference from running a whole Docker container on an ARM system for having a single tool available.

Then what is the difference with running a single tool into an AMD64 container? :)

> it would never cross my mind to spin up a Docker container for it.

It cross my mind everyday to use containers on raspberry PI to test applications and tools without polluting the OS, container does not mean installing the whole docker daemon:
```console does not mean installing

**Comment by MichaIng** [comment]
> What is the difference with running a single tool into an AMD64 container? 😄
> ...
> Also, ARM does not mean only apple or raspberry :)

x86 systems are commonly used for hosting snap/Docker/Kubernetes/VMs/whatever kind of virtualisation and containerisation for server isolation, testing, development, cross-compiling and what not, and then expected to have sufficient power to make this possible. In case of ARMs of course there are either powerful ones there already (the Apple M1 seems to be) or will be coming in the future, but I haven't seen those being used widely at least. But I may have a wrong impression or things may change soon.

> use containers on raspberry PI to test applications and tools without polluting the OS

I'd personally develop and test things on an x86 system, either VM or running some QEMU/binfmt emulation for ARM, but yes probably the recent SBCs are increasingly well capable to do it there as well.

> podman run -it lycheeverse/lychee

I have to learn about podman. I mean the Docker image/container is still a whole OS (without kernel and alike of course) that needs to be (down)loaded and there is no way around that via `podman`, isn't it? Also, since you have the container with the static binary inside, there is much easier way to secure/isolate the single static `lychee` binary, when not trusting it for some reason, than having a whole container around it 😉.

But don't understand me wrong, often the use cases appear when the option is there and the clear difference between x86 and ARM capabilities is decreasing, so as long as it does not imply too much overhead or maintenance efforts, I'm all in 🙂.

**Comment by fauust** [comment]
> I have to learn about podman.

I encourage you [to](https://github.com/containers/podman). In my case, the reason why I started to prefer it over docker (when possible) was:
- rootless containers;
- better cgroup management (that permits to emulate better systemd).

> Also, since you have the container with the static binary inside, there is much easier way to secure/isolate the single static lychee binary, when not trusting it for some reason, than having a whole container around it wink.

Sure but with containers, you have a command that will manage everything for you (pull, upgrade, run, prune etc.), and the "whole" container is just a bunch of MB layers to pull from the internet ;-) 

I am not saying that containers are always the best option (we are speaking about 100 MB for the `buster-slim` based container vs 5.26 MB for the x64 lychee binary), but in CI context for instance, it's really very nice to have.

> often the use cases appear when the option is there

:+1: 

> so as long as it does not imply too much overhead or maintenance efforts, I'm all in :slightly_smiling_face:.

Let's wait for other's comment, there is no urgency at all...

Before multi-arch support, I guess that there is place for easier improvement (the Dockerfile contains errors and is not optimized), and the lack of description on DockerHub are more problematic IMO.

**Comment by MichaIng** [comment]
> but in CI context for instance, it's really very nice to have.

In our CI workflows the static x86 binary is downloaded and used, which is a 1s step, so I'm sure that no other method is even close to beat that 😉.

**Comment by fauust** [comment]
I am saying that it's "nice to have" not faster (and to compare stuff, you should take cache and network in consideration, I am pretty sure that Microsoft folks knows what they do between GH actions runners and GH assets)...

But as said, 100 MB vs 5.26 MB is not comparable, those are different use cases. But try to implement a lychee step with the drone.io CI you will get my point :smiley_cat:

**Comment by MichaIng** [comment]
> you should take cache and network in consideration, I am pretty sure that Microsoft folks knows what they do between GH actions runners and GH assets)...

Not sure what you mean. The container adds another layer of complexity to the network and which cache and what does Microsoft have to do with it? They ship Docker with the GH actions runners but it doesn't need to be used for anything I know about 🤔. It's an interesting topic to me since IMHO (and I may just lack knowledge) Docker is often used in cases where it doesn't make much sense, like exactly in GitHub actions. For this reason I also don't use the [lychee-action](https://github.com/lycheeverse/lychee-action) but download and run the static binary directly on the Ubuntu VM runner, which is much faster, more flexible (full control over version, where and how to execute it), less overhead etc, of course with the one downside that one needs to pull the right binary depending on the chosen VM OS, while lychee-action runs the same way on all of them. It is OOT but I would be very interested to learn why Docker is often used in such cases, what details I miss, in case 🧐.

Drone has moreless the same syntax as GitHub actions, so something like this wouldn't work?
```yaml
steps:
- name: Download lychee
  commands:
  - curl -sSfL "$(curl -sSfL https://api.github.com/repos/lycheeverse/lychee/releases/latest | mawk -F\" '/"browser_download_url.*x86_64-unknown-linux-gnu\.tar\.gz"/{print $4;exit}')" -o lychee.tar.gz
  - tar xf lychee.tar.gz
- name: Run lychee
  commands:
  - ./lychee 'build/**/*.html'
```

But unrelated to that, I agree it's good to have the Docker container, also for ARM ✌️.

**Comment by fauust** [comment]
@MichaIng before making your opinion on a technology, you may want to first understand it better. Don't take it personally (or bad) and I like your concerns about not using Docker when not necessary (and yes sometimes you do not want to use a technology just because it's trendy and why use containers when you seem to be more comfortable with `curl`?)

It's important to understand what we do and so, to use the technology that we feel more comfortable with.

But if it's OK with you let's see what other's opinion are about this issue/proposition.

**Comment by lebensterben** [comment]
There's a joke that some countries are good at solving problems nobody else ever has.
It's probably also true to say that some programming language community is really good at solving issues others don't have.
One reason people needs Docker is to avoid dependency hell, either due to crappy development toolchain, or due to incompatibility introduced by OS upgrades.

But Rust has awesome toolchain and guarantees that the source code always compiles. And lychee doesn't have external dependency that is breakable. (If libc is broken you should expect nothing to work.) I don't think it's ever needed to use Docker for our use case.

**Comment by fauust** [comment]
I am not suggesting using Docker for "our" use case nor in the actual GitHub action CI but to propose more architecture in case some users find it useful...

Also I am not sure that this project (any project?) should decide what is good and what is not for users but I am a new comer so please let me know this is the case.

**Comment by mre** [comment]
If we can support more platforms without a lot more maintenance work, we should. I for one use the lychee binaries as well as the container depending on the environment. While I don't use non-x64 containers I don't see why we shouldn't support that.

The [current Docker CI](https://github.com/lycheeverse/lychee/blob/master/.github/workflows/docker.yml) only has 23 lines, which is very convenient. It also has snapshot and semver support. I'd love to keep those features.

@fauust we could perhaps start by adding the missing Docker description and tackle the other architectures in a separate pull request.

**Comment by fauust** [comment]
> @fauust we could perhaps start by adding the missing Docker description and tackle the other architectures in a separate pull request.

PR already done for the description:
https://github.com/lycheeverse/lychee/pull/325

Agree for the rest.

**Comment by fauust** [comment]
We probably want to handle this better too in the future:
https://github.com/fauust/lychee/runs/3599163361?check_suite_focus=true

![screenshot_20210914_153704](https://user-images.githubusercontent.com/2197555/133268135-a874ad8b-a79c-413c-bd52-9fd17716da36.png)

**Comment by MichaIng** [comment]
You mean skipping the publish step if it runs on a fork?

**Comment by fauust** [comment]
For instance yes.

On other project I use a local registry and build and push on the local registry and skip the push to DockerHub (that is done only from the upstream repo). This way forks also execute most part of the container building CI.

**Comment by lebensterben** [comment]
> While I don't use non-x64 containers I don't see why we shouldn't support that.

Spending electricity on building something nobody is gonna use is just another way of making more carbon dioxide and killing the planet.

**Comment by MichaIng** [comment]
Consequently then it would be the first task to turn the lychee action into a pure binary download + execution one, as the majority of GitHub users likely use the action instead of doing what I do (downloading and running it directly in the workflow). And the accumulated CPU time and network traffic overhead implied with the Docker image is much larger than doing a first build of an ARM Docker container and see whether somebody is gonna use it or not 😉.

While I had the exactly same thoughts in my mind (waste or network and CPU capacities => CO2 emissions and getting used to not think about such such things at all when using free online services, which is IMO really a problem), I wouldn't do project decisions based on it, but instead doing such discussion on a personal level and showing people the alternatives, and in case learned about up/downsides. But so far I still miss a good reason why lychee and very most other similar linter and checker tools (liche, HTML/CSS validators etc etc) all come as a Docker container, often with much limited possibilities to define command line arguments etc (lychee is great in this regards). I do direct downloads of the actual cmd tool in all of these cases and have not a single idea why doing different would be of any benefit in a GitHub action. In a secured own environment where for security reasons you want every service and tool to run sandboxed, there are use cases, of course.

**Comment by mre** [comment]
@fauust covered most issues mentioned:
* [X] Add basic image description on Docker registry (#325)
* [X] Optimize Dockerfile (#326)
* [X] skip publish step if it runs on a fork

The remaining bit is multi-arch support.

I'm all for supporting arm64 (for Apple Silicon) at least as it's gaining a lot of popularity.
(Especially in the Rust community; I will be a user myself.)
@fauust would you like to create a PR for that?

**Comment by fauust** [comment]
See: https://github.com/lycheeverse/lychee/pull/406
There is a huge build time problem on the CI runner (it may come from the QEMU emulation of docker buildkit).
We could also build on a MacOS X runner (not sure if those are ARM though).

**Comment by MichaIng** [comment]
Why does it use QEMU emulation instead of doing common cross compiling with native architecture toolkit? Emulation of course is very slow, especially when it's done for compiling software which requires a whole lot of binary calls all wrapped by the emulator.

Isn't it possible to use a light pre-compiled Docker base container for `aarch64` and place the previously compiled `aarch64` lychee binary inside? So no additional compiling required? Probably dump, I just have no experience with Docker container builds, but this would be the first thing I'd try.

**Comment by mre** [comment]
Yeah the latest macOS image is `macos-11` with
```
> uname -a
Darwin Mac-1637786579865.local 20.6.0 Darwin Kernel Version 20.6.0: Tue Oct 12 18:33:42 PDT 2021; root:xnu-7195.141.8~1/RELEASE_X86_64 x86_64
```

There is an [issue for arm support](https://github.community/t/ask-about-github-hosted-runners-arm64-platform-support/167483), but it's not on the roadmap yet.

**Comment by mre** [comment]
QEMU seems to be extremely slow. 
Numerous tickets on this topic:
* https://github.com/uraimo/run-on-arch-action/issues/4
* https://github.com/rootwyrm/dns_docker/issues/5
* https://github.com/scikit-learn/scikit-learn/issues/19027

Some people use Travis, which has native hardware.
In our case we could also look into cross-compiling as @MichaIng suggested.
😕

**Comment by fauust** [comment]
@MichaIng, that's a perfectly good approach!
And this is also the most optimal, as we currently build x64 binary twice (release job and docker job).

I'll check how this can be done in the GitHub action context (maybe depending off the release job and fetching the binary directly from GitHub is the cleanest solution).

Please can you answer the following:
- which binary do we want to use in docker?
- should we keep the actual Dockerfile (is it used elsewhere, in build test for instance)?

BTW, the release CI is [red](https://github.com/lycheeverse/lychee/actions/runs/1474282935), I don't know if that's ok?

**Comment by mre** [comment]
> which binary do we want to use in docker?

I guess we should use the latest binary compiled from `master` whenever we build the image. This way we'll make sure that the image is ready for release. `lycheeverse/lychee:latest` gets pushed on merge to `master` and if we create a release it will tag and push the image with the release tag.

> should we keep the actual Dockerfile (is it used elsewhere, in build test for instance)?

I don't think it's used anywhere right now, but I wouldn't mind keeping it so that people can inspect it and send PRs easily.
We could create a `docker` folder and add `Dockerfile-amd64` and `Dockerfile-arm64` there and refer to them in the pipeline with `docker build -f docker/Dockerfile-arm64 ...` for example.

**Comment by mre** [comment]
Seems like we have some problems with the `musl` builds:

```
  = note: /target/arm-unknown-linux-musleabihf/release/deps/libopenssl_sys-547d4accb3e79e8e.rlib(libcrypto-lib-threads_pthread.o): In function `CRYPTO_atomic_or':
          /target/arm-unknown-linux-musleabihf/release/build/openssl-sys-92783db41161d9a1/out/openssl-build/build/src/crypto/threads_pthread.c:220: undefined reference to `__sync_or_and_fetch_8'
          /target/arm-unknown-linux-musleabihf/release/deps/libopenssl_sys-547d4accb3e79e8e.rlib(libcrypto-lib-threads_pthread.o): In function `CRYPTO_atomic_load':
          /target/arm-unknown-linux-musleabihf/release/build/openssl-sys-92783db41161d9a1/out/openssl-build/build/src/crypto/threads_pthread.c:245: undefined reference to `__sync_val_compare_and_swap_8'
          collect2: error: ld returned 1 exit status
```
https://github.com/lycheeverse/lychee/runs/4245580796?check_suite_focus=true

The error message is suspicious. Maybe something about gcc-musl.

**Comment by fauust** [comment]
> I guess we should use the latest binary compiled from master whenever we build the image. This way we'll make sure that the image is ready for release. lycheeverse/lychee:latest gets pushed on merge to master and if we create a release it will tag and push the image with the release tag.

Sorry, I was not clear enough. I was wondering which (in the latest one) binary should we use, I see various:
- x86_64-unknown-linux-gnu
- x86_64-unknown-linux-musl
- arm-unknown-linux-gnueabihf
- arm-unknown-linux-musleabi
- arm-unknown-linux-musleabihf
- aarch64-unknown-linux-gnu

> I don't think it's used anywhere right now, but I wouldn't mind keeping it so that people can inspect it and send PRs easily.
We could create a docker folder and add Dockerfile-amd64 and Dockerfile-arm64 there and refer to them in the pipeline with docker build -f docker/Dockerfile-arm64 ... for example.

:+1:

**Comment by MichaIng** [comment]
The `musl` binaries are usually smaller, but otherwise I'm not sure of differences or downsides. Since at least recently some `musl` builds fail, that would be an argument to use the `GNU` ones, or at least have a fallback.

Among the three ARM ones, I think there is no point in supporting ARMs without floating-point hardware (?), so I'd use a `*hf` one. This means it's ARMv7 + probably the special Raspberry Pi 1/Zero ARMv6hf architecture supported. I'll check whether the latter is true.

**Comment by mre** [comment]
Yup we can take `arm-unknown-linux-gnueabihf` if that works.

**Comment by fauust** [comment]
> Yup we can take `arm-unknown-linux-gnueabihf` if that works.

It doesn't (at least on raspberry pi4 and on some ARM machine tested). So I am using `lychee-v0.8.1-aarch64-unknown-linux-gnu.tar.gz` for now.

**Comment by MichaIng** [comment]
> It doesn't (at least on raspberry pi4 and on some ARM machine tested).

??? This does definitely works on ARMv7 and ARMv8 capable RPi models. You obviously run a 64-bit image, so using the aarch64 binary is the obvious correct choice, but even then, armhf and also non-hf binaries should be executed just fine, when not depending on shared armhf libraries. So if it does not work, would be interesting what error message is given, and which image/OS you use, as then we had a problem.

The question was whether it works ARMv6-only capable RPi models, RPi 1 and Zero (1), everything else shouldn't be an issue at all.

**Comment by fauust** [comment]
@MichaIng I am not sure that I understand what you are talking about. I was just asking for which binary I should use to make the docker ARM image compatible with most of ARM architectures (and of course Apple Silicon).
So you tell me :)

The image that raspberry use is https://hub.docker.com/layers/debian/library/debian/bullseye-slim/images/sha256-3da6322809c63296f41e7ec624178ad0aafa5d505514b33a892291716f694cd7?context=explore

And the error is the following:
```console
❯ podman build . -f ci.Dockerfile
STEP 1: FROM debian:bullseye-slim
STEP 2: RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y     --no-install-recommends ca-certificates tzdata wget jq     && rm -rf /var/cache/debconf/*     && apt-get clean     && rm -rf /var/lib/apt/lists/*
--> Using cache 8d9f4837739f6c80814530bbf81dfd27e52cb9d86860b25b14f35508a5672fd3
--> 8d9f4837739
STEP 3: RUN case $(dpkg --print-architecture) in     "amd64")       wget -q -O - "$(wget -q -O- https://api.github.com/repos/lycheeverse/lychee/releases/latest       | jq -r '.assets[].browser_download_url'       | grep x86_64-unknown-linux-gnu)" | tar -xz lychee     ;;     "arm64")       wget -q -O - "$(wget -q -O- https://api.github.com/repos/lycheeverse/lychee/releases/latest       | jq -r '.assets[].browser_download_url'       | grep  arm-unknown-linux-gnueabihf)" | tar -xz lychee     ;;   esac   && mv lychee /usr/local/bin/   && chmod +x /usr/local/bin/lychee
--> 13719e44256
STEP 4: ENTRYPOINT [ "lychee" ]
STEP 5: COMMIT
--> 94afc307210
94afc307210fa50e357ea6d94337621a5c1888e9fd6bd6f78b62dc7638f31f0f

❯ podman run -it 94afc307210 --version
standard_init_linux.go:219: exec user process caused: no such file or directory
```
Here is the log with the `aarch64-unknown-linux-gnu binary`:
```console
❯ podman build . -f ci.Dockerfile
STEP 1: FROM debian:bullseye-slim
STEP 2: RUN apt-get update     && DEBIAN_FRONTEND=noninteractive apt-get install -y     --no-install-recommends ca-certificates tzdata wget jq     && rm -rf /var/cache/debconf/*     && apt-get clean     && rm -rf /var/lib/apt/lists/*
--> Using cache 8d9f4837739f6c80814530bbf81dfd27e52cb9d86860b25b14f35508a5672fd3
--> 8d9f4837739
STEP 3: RUN case $(dpkg --print-architecture) in     "amd64")       wget -q -O - "$(wget -q -O- https://api.github.com/repos/lycheeverse/lychee/releases/latest       | jq -r '.assets[].browser_download_url'       | grep x86_64-unknown-linux-gnu)" | tar -xz lychee     ;;     "arm64")       wget -q -O - "$(wget -q -O- https://api.github.com/repos/lycheeverse/lychee/releases/latest       | jq -r '.assets[].browser_download_url'       | grep  aarch64-unknown-linux-gnu)" | tar -xz lychee     ;;   esac   && mv lychee /usr/local/bin/   && chmod +x /usr/local/bin/lychee
--> Using cache 2709aa491ad976a9d0d62edd9ce022d0821976fd915d3360b5afa0a6ab2b6fcb
--> 2709aa491ad
STEP 4: ENTRYPOINT [ "lychee" ]
--> Using cache 68395470c07c6ba4bd141aa4d1cd00300a09126b777d1d146940e27234fc4a4e
--> 68395470c07
68395470c07c6ba4bd141aa4d1cd00300a09126b777d1d146940e27234fc4a4e

❯ podman run -it 68395470c07 --version
lychee 0.8.1
```

If someone wants to test on the Apple Silicon (I personally do not have apple machines to test), you can fetch the `ci.Dockerfile` from  #406 and adapt the `case` statement to fetch the binary that you want to test.

**Comment by fauust** [comment]
BTW, now that we are no building the binary in the docker build CI, I can adapt #406 to generate also other arm arch, see https://hub.docker.com/_/debian?tab=tags&page=1&name=bullseye-slim for the list of available arm arch.

**Comment by MichaIng** [comment]
Ah okay, it's probably the aarch64 container which denies executing armhf binaries even that the host CPU would be able to? Could you try to do this in an armv6l/armv7l container/host system and adjust the dpkg architecture accordingly:
```sh
"armhf")
       wget -q -O - "$(wget -q -O- https://api.github.com/repos/lycheeverse/lychee/releases/latest | jq -r '.assets[].browser_download_url' | grep arm-unknown-linux-gnueabihf)" | tar -xz lychee;;
```

**Comment by fauust** [comment]
> Could you try to do this in an armv6l/armv7l container/host system and adjust the dpkg architecture accordingly:

Unfortunately, I do not have armv6l/armv7l architectures to test :(

> **EDIT: Ah, or the "file not found" error is as there was no `armhf` case handled while it was an `armhf` container?**

My understanding is that you assumed correctly, the file is there (I have test to download and execute it manually), plus the build would have failed with `mv: cannot stat 'lychee': No such file or directory`.

**Comment by MichaIng** [comment]
Okay just to verify: It is an aarch64/arm64 host, so `case $(dpkg --print-architecture) in "arm64")` is matched and the file does actually download, and indeed it must have, since `chmod` succeeded, but then `standard_init_linux.go:219: exec user process caused: no such file or directory` happens? I know such indeed when trying to execute a foreign/unsupported binary, shells print such error, which is a little misleading as the file is there, but in fact it cannot be executed. As said, armv6l/armv7l/armhf binaries usually do execute fine on aarch64 systems, as long as they do not depend on shared libraries, but probably Docker is stricter somehow. Generally it makes sense to only download the the armhf binary if `"armhf")` matches and we'd need an armv7l host to test it + an armv6l host to verify whether this works as well. Wouldn't be a big issue if not as it is only required for the small number of old Raspberry Pi models. I can test the binary itself on a Raspberry Pi Zero (1) later.

**Comment by fauust** [comment]
>  I can test the binary itself on a Raspberry Pi Zero (1) later.

Good!

Can you please check what `dpkg --print-architecture` gives on the pi Zero?

**Comment by MichaIng** [comment]
> Can you please check what `dpkg --print-architecture` gives on the pi Zero?

`armhf`. It's this special armv6hf ARM which is the reason why Debian does not run on those and Raspbian was required in the first place. On Debian `armhf` is ARMv7 compatible only, so the Debian `armhf` binaries do not run on Raspberry Pi 1 and Zero. Similar thing with Docker containers, where often 32-bit ARM containers do not run, but one needs to search for such which are tagged for Raspberry Pi explicitly.

I just tested https://github.com/lycheeverse/lychee/releases/download/v0.8.1/lychee-v0.8.1-arm-unknown-linux-gnueabihf.tar.gz on RPi Zero, and it works fine 🥳! But I'm sure the `debian:bullseye-slim` container does not. Just found this one: https://hub.docker.com/r/tianon/raspbian
```sh
FROM tianon/raspbian:bullseye-slim
```

**Comment by mre** [comment]
Guess we can close this issue as the work here is done. Follow up task here: #417.
Feel free to reopen if I'm missing something.
