### ISSUE TITLE
Separate crate for test utilities

### ISSUE THREAD

**Issue by pawroman** [lycheeverse/lychee#62]
Currently, the `test_utils` module is exported as part of the public API.

This is not by design, but rather a simplified version of what it should be: we should extract all shared test/benchmarking functionality into a separate crate. This crate could then be used by unit tests as well as integration tests in the `tests` directory.

The crate could live in the main repo, since cargo supports [workspaces](https://doc.rust-lang.org/1.30.0/book/second-edition/ch14-03-cargo-workspaces.html) natively.

**Comment by mre** [comment]
Guess it won't be that easy. Tried it and the main problem is that we'd need `types::uri::Uri` in the `test_utils` crate and the `lychee-lib` crate. I imported `Uri` from `lychee-lib` in `test_utils`, but for Rust these are different types (because of nominative instead of structural typing).

I get a lot of errors like this:

```
   --> lychee-lib/src/filter/mod.rs:395:37
    |
395 |         assert!(!filter.is_excluded(&website(V6_MAPPED_V4_PRIVATE_CLASS_A)));
    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `types::uri::Uri`, found struct `lychee_lib::types::uri::Uri`
    |
    = note: expected reference `&types::uri::Uri`
               found reference `&lychee_lib::types::uri::Uri
```

We could use `LabelledGeneric` using [frunk](https://github.com/lloydmeta/frunk) as described [here](https://beachape.com/blog/2021/05/25/structural-typing-in-rust/#quick-review-of-labelledgeneric), but I don't think that's the way to go. Alternatively we could move `Uri` into its own crate, but this would make releases more painful. So... ¯\_(ツ)_/¯

**Comment by mre** [comment]
Guess we can close this as there isn't an easy fix at the moment.
