### ISSUE TITLE
Outdated lychee.example.toml and hard to use

### ISSUE THREAD

**Issue by vpereira01** [lycheeverse/lychee#630]
Hi and props on this great project :)

I'm trying to use a configuration file with lychee-action to improve the readability, as in, to not pollute the action with many arguments and I'm struggling to define a valid configuration file.

Having an updated lychee.example.toml would make it easier for everyone to use it.

Issues I found so far:
* Many command line parameters are missing
   * It seems to me (not a rust developer) that all command line parameters can be defined through the configuration file. Still it's not obvious what the variable names should be.
* The commented example `#accept = "text/html"` does not match the description. The example should be `#accept = "503,403"`
* The `exclude_file = []` should have an example as it's not obvious (to me) that file paths must be quoted, as in, must be strings.

**Comment by mre** [comment]
Hey @vpereira01, thanks for the praise. :)

The example config is definitely out-of-date. We don't have any integration tests for it, so that's why we don't catch these issues automatically yet.

If you have some time, could you create a pull request for fixing the issues you found? 🙇 
Bonus points for adding some documentation for each option.

As you correctly pointed out, all command line parameters should be definable through the configuration file.
There is a list of all options which can occur in the config file here for reference: https://github.com/lycheeverse/lychee/blob/b40aacd459c1351b87375a9dde632cf548942d25/lychee-bin/src/options.rs#L368-L400
I just noticed that some options like `offline` are missing in there. All of the config options from the `Config` struct above should occur in that list. Maybe you have the time to add them there. If not I can take a look later.

**Comment by vpereira01** [comment]
Docs/suggestions updated.

PR ready for Review but I'm not sure how the discovered configuration issues should be handled.
