### ISSUE TITLE
Is there any way to make lychee not to use .lycheeignore or use custom named ignore file?

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee#648]
I want to run lychee in a way that it won't use the .lycheeignore file.
Also is there any way to use a custom named .lycheeignore file (like using a parameter --ignore-file="myignore.txt")

**Comment by mre** [comment]
This used to be possible, but we removed the option a while ago because the option was called `--exclude-file` and people (rightfully) thought it meant "exclude this file from getting checked".
As of now you can't change the lycheeginore filename. We could add it back, but do you have a specific use-case for it? We modeled it after `.gitignore`.

**Comment by Rizwan-Hasan** [comment]
I think having the option will be good, especially we need the option to choose custom ignore file in our use case.

**Comment by mre** [comment]
I'd be willing to accept a pull request for adding it. Just don't know how to name it without confusing people. `--ignore-file` could mean "ignore this file while checking".
Alternatively you could create two config files with different `exclude` sections and set the config via an argument: `--config config1.toml`.

**Comment by Rizwan-Hasan** [comment]
I think first one is better and user can always read the details just typing `--help`

**Comment by Rizwan-Hasan** [comment]
Sounds good and not that confusing.

**Comment by mre** [comment]
Another one, just so that I don't forget: `--exclude-patterns-from`.

**Comment by Rizwan-Hasan** [comment]
This one is good too

**Comment by Rizwan-Hasan** [comment]
Hi @mre
Is there any update regarding the issue?

**Comment by lebensterben** [comment]
what's the use case for using a custom ignore file?

**Comment by Rizwan-Hasan** [comment]
@lebensterben we want to ignore different links in different git actions for the same repository.

**Comment by lebensterben** [comment]
can you show me the CI config?

**Comment by Rizwan-Hasan** [comment]
Here it is https://github.com/allegroai/clearml-docs/blob/main/.github/workflows/links.yml

**Comment by lebensterben** [comment]
@Rizwan-Hasan 

I don't get it.
You've only invoked lychee once. How do you plan to use multiple .lycheeignore file.

**Comment by Rizwan-Hasan** [comment]
@lebensterben 

Will invoke lychee twice and each time with a different ignore file. And to do that need some kind of way to specify the ignore file.

**Comment by lebensterben** [comment]
@Rizwan-Hasan 

say you have too ignore file, foo and bar.

before each job, just

ln -s foo .lycheeignore

and

ln -s bar .lycheeignore

(and remove them after the job)

This should suffice.

**Comment by lebensterben** [comment]
@Rizwan-Hasan 

I'm confused also because in the example you don't even have used .lycheeignore once...

**Comment by Rizwan-Hasan** [comment]
@lebensterben 

Actually, that's the original one that I want to add two instances with separate ignore files.
Here's the one that I'm working on right now [https://github.com/Rizwan-Hasan/clearml-docs/blob/lychee_work/.github/workflows/links.yml](https://github.com/Rizwan-Hasan/clearml-docs/blob/lychee_work/.github/workflows/links.yml)

**Comment by lebensterben** [comment]
I propose to postpone this feature request.

---

First .lycheeignore is a specialized dotfile that config lychee-bin regarding what to exclude.

Generally dotfiles are used to provide user a way to specify a set of configuration options to a program.

And in almost all cases, there's an hierarchy of how program decide what config options it uses:

- User-provided CLI option
- Per-project config (via dotfile)
- Per-user config
- System-wide config
- Program defaults

(from high to low priority)

BUT I have never seen any case where a program allows for multiple conflicting config source on the same level. (Your proposal would translate to multiple per-project configs)

So your proposal would lead to a very unorthodox interface design IMO.

---

Second, we try to mirror how similar tools using .*ignore files.

.lycheeignore itself mirrors .gitignore. And the way how lychee-bin uses .lycheeignore mirros how ripgrep uses . gitignore.

Git doesn't allow multiple .gitignore file. Neither does ripgrep allow users to choose what .gitignore file it uses.

Thus your proposal would break the parallel to the other tools and make the learning curve of lychee-bin steeper.

**Comment by mre** [comment]
The difference is that a `.gitignore` is inherent to the repository it's in.
It makes little sense to ignore a different set of files because it's within the same repo. In lychee's case however, a user might indeed want run the link checker with different ignore settings from the same directory &mdash; there is no concept of a repository. Granted, there are project folders, but in the case of remote URLs as inputs one could argue that the current directory doesn't matter.

**Comment by mre** [comment]
To keep the issue tracker clean and because there is a workaround, I've decided to close the issue.
The workaround is to symlink the `.lycheeignore` file before calling lychee as @lebensterben described:

```
# Run 1
ln -s foo .lycheeignore
lychee ...

# Run 2
ln -s bar .lycheeignore
lychee ...
```

It's not as straightforward as a dedicated commandline parameter, but naming things is hard and we already made the mistake of picking a name that was confusing for some people. I want to avoid making the same mistake and from the naming options I mentioned so far I don't like any on second thought. So let's defer that decision for now. We can revisit the case later if we want. Hope that's okay with everyone. ✌️
