### ISSUE TITLE
Add status code to Markdown output

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#672]
To make troubleshooting situations like https://github.com/lycheeverse/lychee-action/issues/138 easier, we should add the status code to the Markdown output. This is a regression from refactoring.

**Comment by walterbm** [comment]
@mre I would be glad to help with this issue if it is open to outside contributors!

To confirm — the issue is that when using `--format markdown` the final output only shows a generic "Network error" message when a link errors out and since that message is too vague it needs to be updated to include the status code for the failure?

So for example when running this:
```
cargo run -- --verbose --format markdown fixtures/TEST_GITHUB_404.md                                                                                 
```
which returns this output:
```
## Summary

| Status        | Count |
|---------------|-------|
| 🔍 Total      | 1     |
| ✅ Successful | 0     |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 0     |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 1     |

## Errors per input
### Errors in fixtures/TEST_GITHUB_404.md
* [https://github.com/mre/idiomatic-rust-doesnt-exist-man](https://github.com/mre/idiomatic-rust-doesnt-exist-man): Failed: Network error
```
The output should be updated to include the status code and return something like "Failed: Network error (status code: 404)"?

**Comment by mre** [comment]
You got it. I'd be happy for your contribution. Thanks for looking into it.
