### ISSUE TITLE
Treat .mdx extension as Markdown

### ISSUE THREAD

**Issue by tillprochaska** [lycheeverse/lychee#841]
Thanks a lot for working on such an extensive link checking tool! I tried out lychee for a documentation site that uses [MDX](https://mdxjs.com/), a Markdown superset.

When I run `lychee --base docs/ docs/**/*.mdx` it does extract absolute URLs correctly, but ignores relative (internal) URLs.

I think this is because lychee detects the file type as plaintext, as the extension is neither `.md` nor `.markdown`. If I change the file extension from `.mdx` to `.md`, lychee detects all URLs as expected, including relative interal URLs.

It would be nice to either add `.mdx` to the hard-coded list of Markdown-ish extensions or to add a configuration option that allows to override/customize the default file type detection.

I’d be open to create a PR to implement and test the first solution. Not sure my Rust knowledge is good enough to implement a more flexible solution though.

**Comment by mre** [comment]
Interesting. Yeah I agree that we should add support for it.
If we find that there are no issues with `.mdx` files in general I'd be okay with adding it to `FileType::Markdown` as another valid extension. Otherwise we could add a new `FileType` if needed.

Perhaps somewhat interestingly, ripgrep presently does not support `.mdx` either. There is an open pull request to add it, though: https://github.com/BurntSushi/ripgrep/pull/2142.

Furthermore, we should add support for overwriting filetypes. ripgrep supports this:

```
-t, --type TYPE ...
    Only search files matching TYPE. Multiple type flags may be provided. Use the
    --type-list flag to list all available types.

    This flag supports the special value all, which will behave as if --type was
    provided for every file type supported by ripgrep (including any custom file
    types). The end result is that --type all causes ripgrep to search in
    "whitelist" mode, where it will only search files it recognizes via its type
    definitions.
```

Then a user could say `lychee --type md --type mdx`
The ripgrep file handling is quite [sophisticated](https://github.com/BurntSushi/ripgrep/blob/master/GUIDE.md#manual-filtering-file-types). I personally think it's more than what we need.
Therefore an alternative might be to use `--include-type` and `--exclude-type` instead, which might be more fitting with the rest of the options.

Open for suggestions here.

**Comment by tillprochaska** [comment]
> Interesting. Yeah I agree that we should add support for it.
If we find that there are no issues with .mdx files in general I'd be okay with adding it to FileType::Markdown as another valid extension.

Any specific requirements in order to consider `.mdx` files working without problems? In general, MDX is a superset of Markdown that adds support for ESM imports/export as well as JSX:

```
// import
import { Greeting, Container } from 'package';

// export
export const foo = 'bar';

// JSX
<Greeting name="John Doe" />
```

https://github.com/mdx-js/specification#mdx

Most Markdown parsers I’ve come across so far would simply treat this as plaintext or HTML. Haven’t found any specific information for `pulldown-cmark`, but so far it has worked fine in all cases I tested.

The only relevant aspect probably is that Markdown can be nested inside of JSX elements. In these cases, lychee would need to extract  links in nested elements:

```
<Container>
  [This is a link](https://example.org)
</Container>
```

I can create a fixture that includes examples for the MDX syntax if that helps?

**Comment by mre** [comment]
Thanks for all the context. From what I can tell there won't be any issues.
I'd be thankful for a pull request to add the extension as well as the test case you describe. 👍

**Comment by tillprochaska** [comment]
Cool, I’ll take a look and will try top open a PR sometime next week :)

**Comment by mre** [comment]
Thanks!

**Comment by mre** [comment]
Went ahead and added `mdx` and some other common extensions. Thanks for the suggestion @tillprochaska. 😃
