### ISSUE TITLE
TOML parse error on `base`

### ISSUE THREAD

**Issue by kytta** [lycheeverse/lychee#964]
I am trying to configure lychee to scan links on my website. Here's a part of my lychee.toml:

```toml
# Base URL or website root directory to check relative URLs.
base = "https://www.kytta.dev"
```

When I try to run it, I get a weird error:

```sh
$ RUST_BACKTRACE=1 lychee './**/*.md'
Error: TOML parse error at line 21, column 8
   |
21 | base = "https://www.kytta.dev"
   |        ^^^^^^^^^^^^^^^^^^^^^^^
invalid type: string "https://www.kytta.dev", expected a borrowed string
```

**Comment by mre** [comment]
This should be [fixed in master](https://github.com/lycheeverse/lychee/commit/7874195bbbe17badaa0a380df3fc94959b87cffd#diff-77e6b4d7040d1a388276416b98a9a5ce205b316b4bfa2c9065d94d27760689dfR75-R81) now and will be released with the next version. If you want to test it, you can build lychee from the sources as there are no pre-built binaries for it. 😉

**Comment by kytta** [comment]
Thank you for the quick reply and for the fix, building from `master` works!

**Comment by mre** [comment]
No worries. I should have caught that one way earlier, but I recently noticed that not all tests get executed in CI because I was missing some additional cargo flags. This will be fixed as well soon, so this should not break again in the future. Thanks for the heads-up.
